#
# Project:      Turtle Project (Project 0)
#
# Author(s): Noah Bridgeman
#
# Due date:     10:00 p.m., Sunday, September 13
#
# Be sure to include citations in your code where you received help from
# another. Here is the form we would like you to use:

# CITE: Discussion with Teaching Assistant Jack Scacco
# HELP: Suggested additional parameter to combine multiple functions into one

# Reference Image
# https://dynaimage.cdn.cnn.com/cnn/q_auto,w_380,c_fit/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F200518114838-05-pac-man-40.jpg

from turtle import *

def start():
# Put your code here:
    brian = Turtle()
    screen = Screen()
    
    screen.setup(440, 566)
    # Half (220, 283)
    screen.bgcolor("black")
    brian.speed(25)
    screen.tracer(False)
    
    # Outer Line - Top Half
    brian.color("#2121DE")
    brian.pensize(2)
    brian.up()
    brian.goto(-209, 26)
    brian.down()
    brian.fd(74)
    brian.up()
    brian.fd(2)
    brian.left(90)
    brian.fd(2)
    brian.down()
    brian.fd(40)
    brian.up()
    brian.fd(2)
    brian.left(90)
    brian.fd(2)
    brian.down()
    brian.fd(67)
    brian.up()
    brian.goto(-209, 78)
    brian.down()
    brian.left(90)
    brian.circle(8, 90)
    brian.up()
    brian.goto(-209, 78)
    brian.left(90)
    brian.down()
    brian.fd(127)
    brian.up()
    brian.goto(-201, 214)
    brian.down()
    brian.left(90)
    brian.circle(8, 90)
    brian.up()
    brian.goto(-201, 214)
    brian.left(90)
    brian.down()
    brian.goto(0, 214)
    brian.up()
    brian.goto(209, 26)
    brian.down()
    brian.fd(-74)
    brian.up()
    brian.fd(-2)
    brian.left(-90)
    brian.fd(-2)
    brian.down()
    brian.fd(-40)
    brian.up()
    brian.fd(-2)
    brian.left(-90)
    brian.fd(-2)
    brian.down()
    brian.fd(-67)
    brian.up()
    brian.goto(209, 78)
    brian.down()
    brian.left(-90)
    brian.circle(8, -90)
    brian.up()
    brian.goto(209, 78)
    brian.left(-90)
    brian.down()
    brian.fd(-127)
    brian.up()
    brian.goto(201, 214)
    brian.down()
    brian.left(-90)
    brian.circle(8, -90)
    brian.up()
    brian.goto(201, 214)
    brian.left(-90)
    brian.down()
    brian.goto(0, 214)
    
    # Inner Line - Top Half
    brian.pensize(1)
    brian.up()
    brian.goto(-209, 21)
    brian.down()
    brian.fd(76)
    brian.goto(-129, 27)
    brian.seth(90)
    brian.fd(44)
    brian.goto((brian.xcor()-4, brian.ycor()+4)) 
    brian.seth(180)
    brian.fd(67)
    brian.goto((brian.xcor()-4, brian.ycor()+4))
    brian.seth(90)
    brian.fd(127)
    brian.goto((brian.xcor()+4, brian.ycor()+4))
    brian.goto(-11, brian.ycor())
    brian.goto(-7, brian.ycor()-7)
    brian.seth(270)
    brian.fd(50)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.goto(0, brian.ycor())
    brian.up()
    brian.goto(209, 21)
    brian.seth(180)
    brian.down()
    brian.fd(76)
    brian.goto(129, 27)
    brian.seth(90)
    brian.fd(44)
    brian.goto((brian.xcor()+4, brian.ycor()+4)) 
    brian.seth(0)
    brian.fd(67)
    brian.goto((brian.xcor()+4, brian.ycor()+4))
    brian.seth(90)
    brian.fd(127)
    brian.goto((brian.xcor()-4, brian.ycor()+4))
    brian.goto(11, brian.ycor())
    brian.goto(7, brian.ycor()-7)
    brian.seth(270)
    brian.fd(50)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.goto(-1, brian.ycor())
    
    # Outer Line - Bottom Half
    brian.color("#2121DE")
    brian.pensize(2)
    brian.up()
    brian.goto(-209, -15)
    brian.down()
    brian.seth(0)
    brian.fd(74)
    brian.up()
    brian.fd(2)
    brian.left(-90)
    brian.fd(2)
    brian.down()
    brian.fd(40)
    brian.up()
    brian.fd(2)
    brian.left(-90)
    brian.fd(2)
    brian.down()
    brian.fd(67)
    brian.up()
    brian.goto(-209, -67)
    brian.down()
    brian.left(90)
    brian.circle(8, -90)
    brian.up()
    brian.goto(-209, -67)
    brian.left(90)
    brian.down()
    brian.fd(157)
    brian.up()
    brian.goto(-201, -233)
    brian.down()
    brian.left(90)
    brian.circle(8, -90)
    brian.up()
    brian.goto(-201, -233)
    brian.left(-90)
    brian.down()
    brian.goto(0, -233)
    brian.up()
    brian.goto(209, -15)
    brian.down()
    brian.seth(0)
    brian.fd(-74)
    brian.up()
    brian.fd(-2)
    brian.left(90)
    brian.fd(-2)
    brian.down()
    brian.fd(-40)
    brian.up()
    brian.fd(-2)
    brian.left(90)
    brian.fd(-2)
    brian.down()
    brian.fd(-67)
    brian.up()
    brian.goto(209, -67)
    brian.down()
    brian.left(-90)
    brian.circle(8, 90)
    brian.up()
    brian.goto(209, -67)
    brian.left(-90)
    brian.down()
    brian.fd(-157)
    brian.up()
    brian.goto(201, -233)
    brian.down()
    brian.left(-90)
    brian.circle(8, 90)
    brian.up()
    brian.goto(201, -233)
    brian.left(-90)
    brian.down()
    brian.goto(-1, -233)
    
    # Inner Line - Bottom Half
    brian.pensize(1)
    brian.up()
    brian.goto(-209, -9)
    brian.down()
    brian.fd(77)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(47)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(67)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(66)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(22)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(22)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(67)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.goto(1, brian.ycor())
    brian.up()
    brian.goto(209, -9)
    brian.seth(180)
    brian.down()
    brian.fd(77)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(47)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(67)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(66)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(22)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(22)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(67)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.goto(-1, brian.ycor())
    
    # Shorter Rectangles
    brian.pensize(1)
    brian.seth(0)
    brian.up()
    brian.goto(-220+51, 283-105)
    brian.down()
    for _ in range(2):
        brian.fd(36)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(20)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    brian.seth(0)
    brian.up()
    brian.goto(220-87, 283-105)
    brian.down()
    for _ in range(2):
        brian.fd(36)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(20)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    # Longer Rectangles
    brian.pensize(1)
    brian.seth(0)
    brian.up()
    brian.goto(-220+127, 283-105)
    brian.down()
    for _ in range(2):
        brian.fd(50)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(20)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    brian.seth(0)
    brian.up()
    brian.goto(220-177, 283-105)
    brian.down()
    for _ in range(2):
        brian.fd(50)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(20)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    # Shorter Oval Pieces
    brian.pensize(1)
    brian.seth(0)
    brian.up()
    brian.goto(-220+51, 283-168)
    brian.down()
    for _ in range(2):
        brian.fd(36)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(5)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    brian.seth(0)
    brian.up()
    brian.goto(220-87, 283-168)
    brian.down()
    for _ in range(2):
        brian.fd(36)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(5)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    # Longer Oval Pieces
    brian.pensize(1)
    brian.seth(270)
    brian.up()
    brian.goto(-84, -13)
    brian.down()
    for _ in range(2):
        brian.fd(48)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(5)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    brian.seth(270)
    brian.up()
    brian.goto(95, -13)
    brian.down()
    for _ in range(2):
        brian.fd(48)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(5)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    brian.pensize(1)
    brian.seth(0)
    brian.up()
    brian.goto(-93, -96)
    brian.down()
    for _ in range(2):
        brian.fd(48)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(5)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    brian.seth(0)
    brian.up()
    brian.goto(41, -96)
    brian.down()
    for _ in range(2):
        brian.fd(48)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
        brian.fd(5)
        brian.right(45)
        brian.fd(5)      
        brian.right(45)
    
    # Longer, Symmetrical T-Shapes
    brian.seth(0)
    brian.up()
    brian.goto(0, 118)
    brian.down()
    brian.fd(46)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.goto(1, 118)
    
    brian.seth(0)
    brian.up()
    brian.goto(0, -53)
    brian.down()
    brian.fd(46)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.goto(1, -53)
    
    brian.seth(0)
    brian.up()
    brian.goto(0, -139)
    brian.down()
    brian.fd(46)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.goto(1, -139)
    
    # Ghost Box
    brian.up()
    brian.color("#DEA185")
    brian.goto(-16, 31)
    brian.pensize(2)
    brian.seth(0)
    brian.down()
    brian.fd(30)
    brian.color("#2121DE")
    brian.pensize(1)
    brian.up()
    brian.goto(-17, 34)
    brian.seth(180)
    brian.down()
    brian.fd(35)
    brian.left(90)
    brian.fd(56)
    brian.left(90)
    brian.fd(103)
    brian.left(90)
    brian.fd(56)
    brian.left(90)
    brian.fd(35)
    brian.left(90)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.seth(270)
    brian.fd(4)
    brian.goto(brian.xcor()+1, brian.ycor()-1)
    brian.seth(0)
    brian.fd(29)
    brian.right(90)
    brian.fd(45)
    brian.right(90)
    brian.fd(91)
    brian.right(90)
    brian.fd(45)
    brian.right(90)
    brian.fd(29)
    brian.goto(brian.xcor()+1, brian.ycor()+1)
    brian.seth(90)
    brian.fd(4)
    
    
    # L Shapes
    brian.up()
    brian.goto(-167, -96)
    brian.seth(0)
    brian.down()
    brian.fd(35)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(48)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(23)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(4)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.fd(5)
    
    brian.up()
    brian.goto(167, -96)
    brian.seth(180)
    brian.down()
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(48)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(36)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.fd(23)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(4)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(5)
    
    # Asymmetrical T-Shapes
    brian.up()
    brian.goto(-167, -182)
    brian.seth(0)
    brian.down()
    brian.fd(67)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(35)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(36)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.goto(-167, brian.ycor())
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.fd(5)
    
    brian.up()
    brian.goto(167, -182)
    brian.seth(180)
    brian.down()
    brian.fd(67)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(36)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(180)
    brian.goto(167, brian.ycor())
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(5)
    
    # Shorter, Symmetrical T-Shapes
    brian.up()
    brian.goto(-83, 116)
    brian.seth(270)
    brian.down()
    brian.fd(35)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(33)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(33)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(91)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(0)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    
    brian.up()
    brian.goto(83, 116)
    brian.seth(270)
    brian.down()
    brian.fd(35)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(180)
    brian.fd(33)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(33)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(35)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(5)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.seth(90)
    brian.fd(91)
    brian.goto(brian.xcor()-4, brian.ycor()+4)
    brian.seth(180)
    brian.fd(5)
    brian.goto(brian.xcor()-4, brian.ycor()-4)
    brian.seth(270)
    brian.fd(5)
    
    # Dots
    brian.up()
    brian.color("#ffddbf")
    brian.goto(-23, -124)
    brian.seth(180)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.dot(15)
    brian.seth(0)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(25):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(2):
        brian.dot(4)
        brian.fd(15)
    brian.dot(15)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(5):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(8):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(5):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(5):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(9):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(8):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(5):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(12):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(2):
        brian.dot(4)
        brian.fd(15)
    brian.dot(15)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(19):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.dot(15)
    brian.seth(180)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(12):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(3):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(15):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(90)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(7):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(180)
    for _ in range(6):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(270)
    for _ in range(4):
        brian.dot(4)
        brian.fd(15)
    brian.fd(-15)
    brian.seth(0)
    for _ in range(12):
        brian.dot(4)
        brian.fd(15)
    
    # Ghosts and Pac-Man
    brian.up()
    brian.goto(4, -123)
    brian.down()
    brian.dot(22, "#FFFF00")
    brian.up()
    brian.goto(-6, -118)
    brian.color("black")
    brian.down()
    brian.begin_fill()
    brian.goto(7, -123)
    brian.goto(-6, -128)
    brian.goto(-6, -118)
    brian.end_fill()
    
    brian.up()
    brian.goto(-20, 4)
    brian.seth(90)
    brian.color("#1bbaeb")
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.goto(brian.xcor()-4, brian.ycor()+6)
    brian.seth(180)
    brian.fd(2)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.fd(7)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.fd(2)
    brian.goto(brian.xcor()-4, brian.ycor()-6)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(1)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.seth(270)
    brian.fd(13)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(4)
    brian.seth(0)
    brian.fd(5)
    brian.seth(270)
    brian.fd(4)
    brian.seth(0)
    brian.fd(2)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(90)
    brian.fd(13)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.seth(180)
    brian.fd(1)
    brian.end_fill()
    brian.up()
    brian.color("white")
    brian.goto(-39, 1)
    brian.seth(90)
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.seth(0)
    brian.fd(1)
    brian.goto(brian.xcor()+2, brian.ycor()+2)
    brian.goto(brian.xcor()+2, brian.ycor()-2)
    brian.seth(0)
    brian.fd(1)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(6)
    brian.end_fill()
    brian.up()
    brian.goto(-28, 1)
    brian.seth(90)
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.seth(0)
    brian.fd(1)
    brian.goto(brian.xcor()+2, brian.ycor()+2)
    brian.goto(brian.xcor()+2, brian.ycor()-2)
    brian.seth(0)
    brian.fd(1)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(6)
    brian.end_fill()
    brian.up()
    brian.goto(-38, 2)
    brian.color("#111dc4")
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    brian.up()
    brian.goto(-27, 2)
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
        
    brian.up()
    brian.goto(11, 26)
    brian.seth(90)
    brian.color("#fcb6db")
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.goto(brian.xcor()-4, brian.ycor()+6)
    brian.seth(180)
    brian.fd(2)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.fd(7)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.fd(2)
    brian.goto(brian.xcor()-4, brian.ycor()-6)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(1)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.seth(270)
    brian.fd(13)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(4)
    brian.seth(0)
    brian.fd(5)
    brian.seth(270)
    brian.fd(4)
    brian.seth(0)
    brian.fd(2)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(90)
    brian.fd(13)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.seth(180)
    brian.fd(1)
    brian.end_fill()
    brian.up()
    brian.goto(-9, 32)
    brian.seth(270)
    brian.color("white")
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.seth(0)
    brian.fd(2)
    brian.seth(270)
    brian.fd(2)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(2)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(4)
    brian.seth(180)
    brian.fd(6)
    brian.end_fill()
    brian.up()
    brian.goto(2, 32)
    brian.seth(270)
    brian.color("white")
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.seth(0)
    brian.fd(2)
    brian.seth(270)
    brian.fd(2)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(2)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(4)
    brian.seth(180)
    brian.fd(6)
    brian.end_fill()
    brian.up()
    brian.goto(-7, 34)
    brian.color("#111dc4")
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    brian.up()
    brian.goto(4, 34)
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    
    brian.up()
    brian.goto(41, 4)
    brian.seth(90)
    brian.color("#ecad30")
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.goto(brian.xcor()-4, brian.ycor()+6)
    brian.seth(180)
    brian.fd(2)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.fd(7)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.fd(2)
    brian.goto(brian.xcor()-4, brian.ycor()-6)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(1)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.seth(270)
    brian.fd(13)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(4)
    brian.seth(0)
    brian.fd(5)
    brian.seth(270)
    brian.fd(4)
    brian.seth(0)
    brian.fd(2)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(90)
    brian.fd(13)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.seth(180)
    brian.fd(1)
    brian.end_fill()
    brian.up()
    brian.color("white")
    brian.goto(21, 1)
    brian.seth(90)
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.seth(0)
    brian.fd(1)
    brian.goto(brian.xcor()+2, brian.ycor()+2)
    brian.goto(brian.xcor()+2, brian.ycor()-2)
    brian.seth(0)
    brian.fd(1)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(6)
    brian.end_fill()
    brian.up()
    brian.goto(32, 1)
    brian.seth(90)
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.seth(0)
    brian.fd(1)
    brian.goto(brian.xcor()+2, brian.ycor()+2)
    brian.goto(brian.xcor()+2, brian.ycor()-2)
    brian.seth(0)
    brian.fd(1)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(6)
    brian.end_fill()
    brian.up()
    brian.goto(22, 2)
    brian.color("#111dc4")
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    brian.up()
    brian.goto(33, 2)
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    
    brian.up()
    brian.goto(-25, 51)
    brian.seth(90)
    brian.color("#ef0305")
    brian.down()
    brian.begin_fill()
    brian.fd(4)
    brian.goto(brian.xcor()-4, brian.ycor()+6)
    brian.seth(180)
    brian.fd(2)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.fd(7)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.fd(2)
    brian.goto(brian.xcor()-4, brian.ycor()-6)
    brian.seth(270)
    brian.fd(4)
    brian.seth(180)
    brian.fd(1)
    brian.goto(brian.xcor()-1, brian.ycor()-1)
    brian.seth(270)
    brian.fd(13)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(0)
    brian.fd(2)
    brian.seth(90)
    brian.fd(4)
    brian.seth(0)
    brian.fd(5)
    brian.seth(270)
    brian.fd(4)
    brian.seth(0)
    brian.fd(2)
    brian.goto(brian.xcor()+4, brian.ycor()+4)
    brian.goto(brian.xcor()+4, brian.ycor()-4)
    brian.seth(90)
    brian.fd(13)
    brian.goto(brian.xcor()-1, brian.ycor()+1)
    brian.seth(180)
    brian.fd(1)
    brian.end_fill()
    brian.up()
    brian.goto(-45, 48)
    brian.color("white")
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    brian.fd(2)
    brian.goto(brian.xcor()+2, brian.ycor()+2)
    brian.seth(90)
    brian.fd(3)
    brian.goto(brian.xcor()-2, brian.ycor()+2)
    brian.seth(180)
    brian.fd(2)
    brian.goto(brian.xcor()-2, brian.ycor()-2)
    brian.seth(270)
    brian.fd(3)
    brian.goto(brian.xcor()+2, brian.ycor()-2)
    brian.end_fill()
    brian.up()
    brian.goto(-34, 48)
    brian.color("white")
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    brian.fd(2)
    brian.goto(brian.xcor()+2, brian.ycor()+2)
    brian.seth(90)
    brian.fd(3)
    brian.goto(brian.xcor()-2, brian.ycor()+2)
    brian.seth(180)
    brian.fd(2)
    brian.goto(brian.xcor()-2, brian.ycor()-2)
    brian.seth(270)
    brian.fd(3)
    brian.goto(brian.xcor()+2, brian.ycor()-2)
    brian.end_fill()
    brian.up()
    brian.goto(-48, 52)
    brian.color("#111dc4")
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    brian.up()
    brian.goto(-37, 52)
    brian.seth(0)
    brian.down()
    brian.begin_fill()
    for _ in range(4):
        brian.fd(3)
        brian.right(90)
    brian.end_fill()
    brian.ht()

    screen.exitonclick()
    
    
# Call the first function -- in this case, it is called "start"

if __name__ == "__main__":
    start()

